version: "3.8"

services:
  app:
    image: easyscripter/dev-tools-hub:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
