name: DevToolsHub CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Build docker image
        run: docker build -t easyscripter/dev-tools-hub:latest .
      - name: LogIn to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: easyscripter/dev-tools-hub:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USER }}
          key: ${{ secrets.REMOTE_SSH_PW }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd ${{ secrets.REMOTE_WORKING_DIR }}
            docker pull easyscripter/dev-tools-hub:latest
            docker stop devtools-hub || true
            docker rm devtools-hub || true
            docker run -d --name devtools-hub -p 3000:3000 easyscripter/dev-tools-hub:latest
